### ISSUE TITLE
Problem with Symmetry

### ISSUE THREAD

**Issue by jdkoenig7** [qucat/qucat#74]
When playing around with the design of the tuneable coupler, I ran into a problem when the capacitors on either side of the coupler are exactly equal.
[tc4.txt](https://github.com/qucat/qucat/files/4793006/tc4.txt)
This problem does not arise in the unmodified version from https://iopscience.iop.org/article/10.1088/1367-2630/ab60f6/pdf .
I seem to be able to fix it by very slightly changing the two capacitances.
![too symmetric qucat](https://user-images.githubusercontent.com/67060067/84907837-fab4aa00-b0b3-11ea-8364-065a1d2b1f8a.png)

**Comment by mgely** [comment]
Hey @jdkoenig7 , 
would you mind copy pasting your code here, so I can reproduce the error?

**Comment by mgely** [comment]
Hi @jdkoenig7, I looked into this issue, and unfortunately there's not much I can do about it...

The problem is indeed that you are trying to simulate a very symmetric problem.
The higher frequency mode of such a coupled system (around 9.5 GHz in this case) , is actually the resonance frequency of both LC oscillators on either side of the coupler.
This means that at that resonance frequency, these LC oscillators will behave as open circuits.

Now why is this a problem? Well multiple things could go wrong.
One example: QuCAT calculates the zero-point fluctuations in flux `phi_zpf` at one "reference" junction, and then will try and calculate what the flux at other junctions is based on this value.
To do this, it uses the fact that flux is proportional to voltage (in frequency space), it fixes an oscillating voltage at the reference junction and calculates using Kirchoff laws what voltage would then occur at the other junctions. In this case, if the voltage oscillates at the 9.5 GHz resonance, then there will be an open circuit somewhere, which results in infinities.

This infinity is theoretically correct, because in this symmetric problem, the voltage across the coupler should be exactly 0.. But zeros and infinities are not very QuCAT-friendly, so small offsets in component values are advised!
