### ISSUE TITLE
coupling between two transmons in quCAT

### ISSUE THREAD

**Issue by amrit-poudel** [qucat/qucat#82]
I was wondering whether there was a way in quCAT to compute coupling strength between two transmons. I saw different methods to compute eigen energies, cross and self kerr, but did not quite find a function to compute the coupling between any two transmons, or between transmons and resonators, etc.

**Comment by mgely** [comment]
There is currectly no way of computing coupling strengths, this is mainly because the normal mode basis is used to write the Hamiltonian rather than the flux or charge basis. Writing a Hamiltonian with a linear coupling between flux or charge variables is a bit dangerous in QuCAT which tries to be as general as possible. Some explanations are given in the paper which originally introduced the normal mode basis for superconducting circuits (see the third paragraph of [1]). 

One problem for implementing what you are asking for, is that the coupling strength one would write in a Hamiltonian does not have a fixed definition. For example, if one starts to include additional modes of the circuit, even modes which are so far detuned they are irrelevant, all the coupling strengths in the Hamiltonian have to change when using the charge or flux basis (see [2]). 

If you really want to get a coupling strength, I would proceed as follows:
 - If you are looking at two far detuned transmons, I would use QuCAT to compute the cross-Kerr interaction and then use that to get a coupling following Eq. (3.12) of [3]
 - If you are looking at resonantly coupled transmons, I would look at the splitting (equal to twice the coupling for usual coupling rates) of an avoided crossing as shown in [this qucat tutorial](https://qucat.org/tutorials/basics.html#Sweeping-a-parameter)

[1] https://arxiv.org/pdf/1204.0587.pdf
[2] https://arxiv.org/pdf/1701.05095.pdf
[3] https://arxiv.org/pdf/cond-mat/0703002.pdf

**Comment by amrit-poudel** [comment]
Thanks for the detailed reply. I appreciate it. Would you not think that the coupling between two quantum objects (e.g. transmon-transmon) are given by the off-diagonal elements of the quantized Hamiltonian  of the composite system (written in many-body representation), even if you choose normal mode basis (by which you mean number state basis, which are eigen states of creation/annihilation operators \hat{a}^{\dag}, \hat{a}).

**Comment by mgely** [comment]
I'll call annihilation operators for the two transmons "a" and "b" and the creation operators "a^" and "b^".

So indeed the normal mode basis is the number basis (eigen states of a^a and b^b). There is however no unique definition of a and b. One can for example define c = (a+b)/sqrt{2] and d = (a-b)/sqrt{2] and then you end up with a different number basis.  Any such linear basis change is possible as long as your new operators satisfy the right commutation relations. You can already see the problem with obtaining a unique definition of the coupling: if you change basis in this way, the coupling will change. The normal mode basis is the basis in which all coupling terms of the form (a+a^)(b+b^) disappear.

In the normal mode basis, off-diagonal components correspond to terms with at least four creation and annihilation operators: a^a^a^b for example. These come from the junction non-linearity. I would recommend you consult the QuCAT paper for further details on this. https://arxiv.org/pdf/1908.10342.pdf

Could you post your other question in our forum? These are not really issues with the code:
https://groups.google.com/g/qucat?pli=1

**Comment by amrit-poudel** [comment]
Thanks for that explanation. Sure, matrix element of a matrix depends on the choice of basis, which is why the basis to be chosen are the number basis or the computational basis ( for two transmons: {00, 01, 10, 11}) where coupling makes sense experimentally. Textbook procedure for circuit quantization is to first write Langrangian --> Hamiltonian --> promote charge/flux  to operators --> write those operators in terms of creation/annihilation operators. The final quantum many-body  Hamiltonian will then be in number basis. Where does the quCAT scheme of "normal mode basis" fit in this standard textbook based circuit quantization?

**Comment by mgely** [comment]
First of all, despite the popularity and pedagogical value of the Devoret review of circuit quantization, quantization in the normal-mode basis (a part of black box quantization) has become the standard in the field for groups using transmon qubits. This is because it most often produces Hamiltonians which are much closer to diagonal than when quantizing in the flux basis. What I mean by this is that the normal mode basis will often produce a Hamiltonians which give realistic results for much smaller Hilbert spaces than in the flux basis. The original paper is by Nigg et al. https://arxiv.org/pdf/1204.0587.pdf , but many other authors have since expanded on this idea.

The way it fits into the standard quantization scheme is by adding an extra step after writing your Lagrangian. At the Lagrangian level, you are free to change flux basis, so if you have two fluxes in your circuit \phi_1, \phi_2, you can introduce \phi_a, \phi_b which are linear combinations of \phi_1, \phi_2. The goal is to eliminate all terms in  \phi_1 x \phi_2, which would eventually become coupling terms in the Hamiltonian. This extra step is described more formally in https://arxiv.org/pdf/1802.10037.pdf equations S3 to S7.

**Comment by mgely** [comment]
I'll close this for now, please head to [our forum](https://groups.google.com/g/qucat?pli=1) if you have more questions of this kind!
